import { useQuery } from 'urql';

import Head from 'next/head';
import { PRODUCT_QUERY } from 'lib/query';
import Product from 'components/Product';
import { Gallery } from '@/styles/Gallery';

export default function Home() {
  // Fetch products from strapi API
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;

  if (fetching) return <p>loading...</p>;
  if (error) return <p>oh no error = {error.message}</p>;

  const products = data.products.data; // title, description, slug, imageUrl

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Gallery>
          {products.map(product => {
            const productData = product.attributes;

            if (!productData) return;

            return <Product key={product.id} data={productData} />;
          })}
        </Gallery>
      </main>
    </>
  );
}
